[package]
name = "meili"
version = "0.1.0"
edition = "2021"

[dependencies]
meilisearch-sdk = "0.17"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
actix-web = "4"
